# Generated by Django 3.2.7 on 2021-09-19 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackmit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=50)),
                ('converted_to_text', models.BooleanField()),
                ('text_path', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
